source 'https://github.com/CocoaPods/Specs.git'

target 'AMGSoundManager', :exclusive => true do
  pod "AMGSoundManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AMGSoundManager", :path => "../"

  
end
